repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-toml
    -   id: requirements-txt-fixer
-   repo: https://github.com/asottile/reorder-python-imports
    rev: v3.17.0
    hooks:
    -   id: reorder-python-imports
        args: [--py310-plus, --add-import, 'from __future__ import annotations']
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v4.0.0
    hooks:
    -   id: add-trailing-comma
-  repo: https://github.com/asottile/pyupgrade
   rev: v3.21.2
   hooks:
   -   id: pyupgrade
       args: [--py310-plus]
-   repo: https://github.com/hhatto/autopep8
    rev: v2.3.2
    hooks:
    -   id: autopep8
-   repo: https://github.com/PyCQA/flake8
    rev: 7.3.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v2.3.0
    hooks:
    -   id: mypy
        args: [--allow-redefinition, --ignore-missing-imports, --config, .mypy.no-config]
    -   id: mypy
        alias: mypy-strict
        name: mypy strict
        args: [--config, pyproject.toml]
        additional_dependencies: [pytest]
        exclude: |
            (?x)(
                itertools\.py
                | ^src/pe_problems/p002\.py$
                | ^src/pe_problems/p005\.py$
                | ^src/pe_problems/p013\.py$
                | ^src/pe_problems/p023\.py$
                | ^src/pe_problems/p032\.py$
                | ^src/pe_problems/p033\.py$
                | ^src/pe_problems/p034\.py$
                | ^src/pe_problems/p036\.py$
                | ^src/pe_problems/p041\.py$
                | ^src/pe_problems/p043\.py$
                | ^src/pe_problems/p049\.py$
                | ^src/pe_problems/p051\.py$
                | ^src/pe_problems/p056\.py$
                | ^src/pe_problems/p057\.py$
                | ^src/pe_problems/p061\.py$
                | ^src/pe_problems/p062\.py$
            )
