"""
Project Euler problem 002: https://projecteuler.net/problem=2

Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.
"""
from itertools import takewhile

from pe.sequences import even_fibonacci_seq



MAX_NUM = 4_000_000

def solve():
    """Solves Project Euler problem 002"""
    lt_4_mil = lambda x: x < MAX_NUM
    even_fibs_under_4_mil = takewhile(lt_4_mil, even_fibonacci_seq())
    total = sum(even_fibs_under_4_mil)

    return str(total)
