# https://black.readthedocs.io/en/stable/integrations/github_actions.html
name: BlackLint

on: ["push"]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
        with:
          options: "--check --verbose --color -l 132"
