name: Project Euler CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'
            - name: Install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install pytest
                if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            - name: Test with pytest
              run: |
                pytest --junitxml=junit/test-results-3.8.xml
            - name: Upload pytest test results
              uses: actions/upload-artifact@v1
              with:
                name: pytest-results-3.8
                path: junit/test-results-3.8.xml